### ISSUE TITLE
The mods won't load

### ISSUE THREAD

**Issue by JohnJaccard** [SilentNightSound/SR-Model-Importer#14]
I start 3DMigotoLoader.exe and after the game.The game start but even after pressing F10 nothing change and the mods just don't work

**Comment by Enferlain** [comment]
Run 3dmigoto as admin

**Comment by sasmwh-hash** [comment]
試試看關掉防毒軟體，並用管理員執行

**Comment by JohnJaccard** [comment]
Thanks sasmwh-hash it works :)
