### ISSUE TITLE
Injector Error injector_inject returned -5

### ISSUE THREAD

**Issue by XieLongWu** [SilentNightSound/SR-Model-Importer#4]
Run in Admin, give out this error.
target = D:\Program Files\Star Rail International\Star Rail\Games\StarRail.exe have set. Both way is same error.
The same error in the International server and the Chinese server.

![QQ截图20230513122412](https://github.com/SilentNightSound/SR-Model-Importer/assets/57319089/224dab80-5593-4930-835e-3d88ecd0ef8b)

**Comment by Aleksimaier2** [comment]
Did you figure out the issue?
